
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-08T12:40:31-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a03f639bc8f439838831582717e2a88f6048725c",
 "version": "2024.5.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
