# Autogenerated import script
# This script is generated based on dependencies listed in pyproject.toml

from generalimport import generalimport

generalimport(
    "aspose", "pdf2docx", "PyPDF2", message="Install with pip install opencf[document]"
)
generalimport(
    "numpy", "cv2", "PIL", "imageio", message="Install with pip install opencf[media]"
)
generalimport("pandas", message="Install with pip install opencf[tabular]")
