
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2024-05-09T21:21:48-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1c5a4e8358b242ae786fd5772a3d7f91286842a6",
 "version": "0.23.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
