# coding: utf-8

"""
    VoiceOS

    VoiceOS API

    The version of the OpenAPI document: 0.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voiceos.models.wako_api_models_phone_number_provider import WakoApiModelsPhoneNumberProvider

class TestWakoApiModelsPhoneNumberProvider(unittest.TestCase):
    """WakoApiModelsPhoneNumberProvider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWakoApiModelsPhoneNumberProvider(self):
        """Test WakoApiModelsPhoneNumberProvider"""
        # inst = WakoApiModelsPhoneNumberProvider()

if __name__ == '__main__':
    unittest.main()
