# coding: utf-8

"""
    VoiceOS

    VoiceOS API

    The version of the OpenAPI document: 0.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voiceos.models.twilio_telephony import TwilioTelephony

class TestTwilioTelephony(unittest.TestCase):
    """TwilioTelephony unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TwilioTelephony:
        """Test TwilioTelephony
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TwilioTelephony`
        """
        model = TwilioTelephony()
        if include_optional:
            return TwilioTelephony(
                provider = 'twilio',
                phone_number_sid = '',
                account_sid = '',
                auth_token = ''
            )
        else:
            return TwilioTelephony(
                provider = 'twilio',
                phone_number_sid = '',
        )
        """

    def testTwilioTelephony(self):
        """Test TwilioTelephony"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
