# coding: utf-8

"""
    VoiceOS

    VoiceOS API

    The version of the OpenAPI document: 0.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voiceos.api.conversations_api import ConversationsApi


class TestConversationsApi(unittest.TestCase):
    """ConversationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConversationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_phone_call(self) -> None:
        """Test case for create_phone_call

        Create Phone Call
        """
        pass

    def test_get_audio_recording(self) -> None:
        """Test case for get_audio_recording

        Get Conversation Recording
        """
        pass

    def test_get_conversation(self) -> None:
        """Test case for get_conversation

        Get Conversation
        """
        pass

    def test_list_conversations(self) -> None:
        """Test case for list_conversations

        List Conversations
        """
        pass


if __name__ == '__main__':
    unittest.main()
