# coding: utf-8

"""
    VoiceOS

    VoiceOS API

    The version of the OpenAPI document: 0.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voiceos.models.voice1 import Voice1

class TestVoice1(unittest.TestCase):
    """Voice1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Voice1:
        """Test Voice1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Voice1`
        """
        model = Voice1()
        if include_optional:
            return Voice1(
                provider = rime,
                model = None,
                speed = None,
                temperature = None,
                text_guidance = None,
                style_guidance = None,
                voice_id = None,
                model_id = 'eleven_multilingual_v2',
                optimize_latency = None,
                use_speaker_boost = None,
                similarity_boost = None,
                stability = None,
                pitch = None,
                rate = None,
                speaker = None,
                speed_alpha = None,
                reduce_latency = None
            )
        else:
            return Voice1(
        )
        """

    def testVoice1(self):
        """Test Voice1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
