# coding: utf-8

"""
    VoiceOS

    VoiceOS API

    The version of the OpenAPI document: 0.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voiceos.models.phone_number_response import PhoneNumberResponse

class TestPhoneNumberResponse(unittest.TestCase):
    """PhoneNumberResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PhoneNumberResponse:
        """Test PhoneNumberResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PhoneNumberResponse`
        """
        model = PhoneNumberResponse()
        if include_optional:
            return PhoneNumberResponse(
                uri = '',
                inbound_agent_id = '',
                phone_number = '',
                account_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                telephony = voiceos.models.twilio_telephony.TwilioTelephony(
                    provider = null, 
                    phone_number_sid = '', 
                    account_sid = '', 
                    auth_token = '', ),
                webhooks = [
                    voiceos.models.phone_number_webhook.PhoneNumberWebhook(
                        events = [
                            'phone_call:connection_requested'
                            ], 
                        url = '', 
                        method = null, 
                        headers = {
                            'key' : ''
                            }, 
                        filter = '', )
                    ],
                id = ''
            )
        else:
            return PhoneNumberResponse(
                uri = '',
                phone_number = '',
                account_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                telephony = voiceos.models.twilio_telephony.TwilioTelephony(
                    provider = null, 
                    phone_number_sid = '', 
                    account_sid = '', 
                    auth_token = '', ),
                id = '',
        )
        """

    def testPhoneNumberResponse(self):
        """Test PhoneNumberResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
