# coding: utf-8

"""
    VoiceOS

    VoiceOS API

    The version of the OpenAPI document: 0.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from voiceos.api.agents_api import AgentsApi


class TestAgentsApi(unittest.TestCase):
    """AgentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgentsApi()

    def tearDown(self) -> None:
        pass

    def test_create_agent(self) -> None:
        """Test case for create_agent

        Create Agent
        """
        pass

    def test_delete_agent(self) -> None:
        """Test case for delete_agent

        Delete Agent
        """
        pass

    def test_get_agent(self) -> None:
        """Test case for get_agent

        Get Agent
        """
        pass

    def test_list_agents(self) -> None:
        """Test case for list_agents

        List Agents
        """
        pass

    def test_update_agent(self) -> None:
        """Test case for update_agent

        Update Agent
        """
        pass


if __name__ == '__main__':
    unittest.main()
