# coding: utf-8

"""
    Montelo API SDK

    This server handles creating traces and logs.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from montelo.client.models.event_queued_dto import EventQueuedDto

class TestEventQueuedDto(unittest.TestCase):
    """EventQueuedDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EventQueuedDto:
        """Test EventQueuedDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EventQueuedDto`
        """
        model = EventQueuedDto()
        if include_optional:
            return EventQueuedDto(
                success = True
            )
        else:
            return EventQueuedDto(
                success = True,
        )
        """

    def testEventQueuedDto(self):
        """Test EventQueuedDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
