"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .passfailunsurerubricscalevalues import PassFailUnsureRubricScaleValues
from dataclasses_json import Undefined, dataclass_json
from gantry import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CriteriaResultCapture:
    r"""CriteriaResultCapture stores current and update values in CriteriaFeedback"""
    score: Optional[PassFailUnsureRubricScaleValues] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('score'), 'exclude': lambda f: f is None }})
    r"""An enumeration."""
    

