# -*- coding: utf-8 -*-
NAME = 'hebill_html'
VERSION = '1.0.1'
DESCRIPTION = 'python生成HTML代码'
LONG_DESCRIPTION = 'README.MD'
LONG_DESCRIPTION_TYPE = 'text/markdown'
URL = 'http://www.hebill.net/'
AUTHOR = 'He Bill'
AUTHOR_EMAIL = 'hebill@hebill.net'
AUTHOR_URL = 'http://www.hebill.net/'
