# coding: utf-8

"""
    Grounding Hub REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from groundinghub.models.direct_completion_request import DirectCompletionRequest

class TestDirectCompletionRequest(unittest.TestCase):
    """DirectCompletionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DirectCompletionRequest:
        """Test DirectCompletionRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DirectCompletionRequest`
        """
        model = DirectCompletionRequest()
        if include_optional:
            return DirectCompletionRequest(
                prompt = 'Show me mounthly income in the form of table for the last quater',
                model_settings = groundinghub.models.model_settings.ModelSettings(
                    model = 'hitachi-genai-platform/HGP-7b-instruct', 
                    params = groundinghub.models.model_params.ModelParams(
                        temperature = 0.9, 
                        top_p = 0.1, 
                        max_tokens = 100, 
                        stop = ["stop","\\n","user:"], ), )
            )
        else:
            return DirectCompletionRequest(
                prompt = 'Show me mounthly income in the form of table for the last quater',
        )
        """

    def testDirectCompletionRequest(self):
        """Test DirectCompletionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
