# coding: utf-8

"""
    Prompt Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from promptrepository.models.tags_type import TagsType

class TestTagsType(unittest.TestCase):
    """TagsType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTagsType(self):
        """Test TagsType"""
        # inst = TagsType()

if __name__ == '__main__':
    unittest.main()
