
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-09T06:26:18-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "65eb315a472b7d9721a86d276bd2a581f775ea31",
 "version": "2024.5.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
