# coding: utf-8

"""
    ContentHub API specification

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from contenthub.api.metadata_api import MetadataApi


class TestMetadataApi(unittest.TestCase):
    """MetadataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetadataApi()

    def tearDown(self) -> None:
        pass

    def test_get_metadata(self) -> None:
        """Test case for get_metadata

        Get a list of distinct metadata
        """
        pass

    def test_get_tags(self) -> None:
        """Test case for get_tags

        Get a list of distinct tags
        """
        pass


if __name__ == '__main__':
    unittest.main()
