CREATE INDEX IF NOT EXISTS "ix_STAFF_LOCATOR_UPI" ON "STAFF_LOCATOR" ("UPI");
CREATE INDEX IF NOT EXISTS "ix_STAFF_LOCATOR_WORK_OUI" ON "STAFF_LOCATOR" ("WORK_OUI");
CREATE INDEX IF NOT EXISTS "ix_STAFF_LOCATOR_WORK_ALPHA" ON "STAFF_LOCATOR" ("WORK_ALPHA");
CREATE INDEX IF NOT EXISTS "ix_STAFF_LOCATOR_WORK_PMU" ON "STAFF_LOCATOR" ("WORK_PMU");
CREATE INDEX IF NOT EXISTS "ix_STAFF_LOCATOR_FIRST_NAME" ON "STAFF_LOCATOR" ("FIRST_NAME");
CREATE INDEX IF NOT EXISTS "ix_STAFF_LOCATOR_LAST_NAME" ON "STAFF_LOCATOR" ("LAST_NAME");
