
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-10T14:51:50-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d84567d1fa53c53fe2ee1a8ca81e86167b7f2f38",
 "version": "2.36.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
