
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-10T09:24:43-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea313f05b945358dd65d624967902c59ce2e0585",
 "version": "5.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
