# generated by datamodel-codegen:
#   filename:  torus.json
#   timestamp: 2024-05-07T15:01:35+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from . import placement


class ITorus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Radius1: float = Field(..., description='The radius of the torus')
    Radius2: float = Field(..., description='The radius of the torus')
    Angle1: float = Field(..., description='The angle of the torus')
    Angle2: float = Field(..., description='The angle of the torus')
    Angle3: float = Field(..., description='The angle of the torus')
    Placement: placement.Model
