from .TamilEnkal import TamilEn
from .TamilEnkal import ArabuEn
from .TamilEnkal import TamilSutru
from .TamilEnkal import ArabuSutru
from .TamilEnkal import Perumam
from .TamilEnkal import Sirumam
from .TamilEnkal import Koottal
from .TamilEnkal import Kazhithal
from .TamilEnkal import Perukkal
from .TamilEnkal import Eevu
from .TamilEnkal import Meedhi
