
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-07T16:53:04-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e20fde8e92fdc36ccca77b8ac7ecefc431d6329e",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
