# Generated by Django 4.1.4 on 2023-12-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_personaldetails_businessprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='onboarding.businessprofile'),
            preserve_default=False,
        ),
    ]
