# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'SetCommandArgs',
]

@pulumi.input_type
class SetCommandArgs:
    def __init__(__self__, *,
                 arguments: pulumi.Input[str],
                 command: pulumi.Input[str],
                 grant: pulumi.Input[str]):
        """
        :param pulumi.Input[str] arguments: Command arguments
        :param pulumi.Input[str] command: Command
        :param pulumi.Input[str] grant: Grant
                 - Choices: `PERMIT`, `DENY`, `DENY_ALWAYS`
        """
        pulumi.set(__self__, "arguments", arguments)
        pulumi.set(__self__, "command", command)
        pulumi.set(__self__, "grant", grant)

    @property
    @pulumi.getter
    def arguments(self) -> pulumi.Input[str]:
        """
        Command arguments
        """
        return pulumi.get(self, "arguments")

    @arguments.setter
    def arguments(self, value: pulumi.Input[str]):
        pulumi.set(self, "arguments", value)

    @property
    @pulumi.getter
    def command(self) -> pulumi.Input[str]:
        """
        Command
        """
        return pulumi.get(self, "command")

    @command.setter
    def command(self, value: pulumi.Input[str]):
        pulumi.set(self, "command", value)

    @property
    @pulumi.getter
    def grant(self) -> pulumi.Input[str]:
        """
        Grant
          - Choices: `PERMIT`, `DENY`, `DENY_ALWAYS`
        """
        return pulumi.get(self, "grant")

    @grant.setter
    def grant(self, value: pulumi.Input[str]):
        pulumi.set(self, "grant", value)


