# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frequenz/api/common/v1/market/energy.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from frequenz.api.common.v1.types import decimal_pb2 as frequenz_dot_api_dot_common_dot_v1_dot_types_dot_decimal__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*frequenz/api/common/v1/market/energy.proto\x12\x1d\x66requenz.api.common.v1.market\x1a*frequenz/api/common/v1/types/decimal.proto\"<\n\x06\x45nergy\x12\x32\n\x03mwh\x18\x01 \x01(\x0b\x32%.frequenz.api.common.v1.types.Decimalb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frequenz.api.common.v1.market.energy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENERGY']._serialized_start=121
  _globals['_ENERGY']._serialized_end=181
# @@protoc_insertion_point(module_scope)
