
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-07T13:35:58+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a8d5d5651568e275ecd7d1b5a5feb0821b927cf3",
 "version": "2.3.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
