# coding: utf-8

"""
    Prompt Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BindingType(str, Enum):
    """
    BindingType
    """

    """
    allowed enum values
    """
    CONSTANT = 'constant'
    QUERY = 'query'
    RAG_MINUS_CONTENT = 'rag-content'
    HISTORY = 'history'
    APP_VARIABLE = 'app_variable'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BindingType from a JSON string"""
        return cls(json.loads(json_str))


