"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

import compas_lcmtypes.geolcm

class twist_t(object):
    __slots__ = ["linear", "angular"]

    __typenames__ = ["compas_lcmtypes.geolcm.vector3_t", "compas_lcmtypes.geolcm.vector3_t"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.linear = compas_lcmtypes.geolcm.vector3_t()
        self.angular = compas_lcmtypes.geolcm.vector3_t()

    def encode(self):
        buf = BytesIO()
        buf.write(twist_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.linear._get_packed_fingerprint() == compas_lcmtypes.geolcm.vector3_t._get_packed_fingerprint()
        self.linear._encode_one(buf)
        assert self.angular._get_packed_fingerprint() == compas_lcmtypes.geolcm.vector3_t._get_packed_fingerprint()
        self.angular._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != twist_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return twist_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = twist_t()
        self.linear = compas_lcmtypes.geolcm.vector3_t._decode_one(buf)
        self.angular = compas_lcmtypes.geolcm.vector3_t._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if twist_t in parents: return 0
        newparents = parents + [twist_t]
        tmphash = (0x3a4144772922add7+ compas_lcmtypes.geolcm.vector3_t._get_hash_recursive(newparents)+ compas_lcmtypes.geolcm.vector3_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if twist_t._packed_fingerprint is None:
            twist_t._packed_fingerprint = struct.pack(">Q", twist_t._get_hash_recursive([]))
        return twist_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", twist_t._get_packed_fingerprint())[0]

