class Fields:
    REPORT_ACCESSION = "report.accession"
    PERIOD_FISCAL_YEAR = "period.fiscal-year"
    PERIOD_END = "period.end"
    PERIOD_FISCAL_PERIOD = "period.fiscal-period"
    FACT_ULTIMUS = "fact.ultimus"
    UNIT = "unit"
    CONCEPT_LOCAL_NAME = "concept.local-name"
    FACT_VALUE = "fact.value"
    FACT_ID = "fact.id"
    ENTITY_ID = "entity.id"
    ENTITY_CIK = "entity.cik"
    ENTITY_NAME = "entity.name"
    REPORT_SIC_CODE = "report.sic-code"
