# Generated by Django 4.2.4 on 2024-03-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_topology_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedtopology',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
