# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from depot_api.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_cluster_clusters_post(self) -> None:
        """Test case for create_cluster_clusters_post

        Create Cluster
        """
        pass

    def test_create_job_instance_job_instances_post(self) -> None:
        """Test case for create_job_instance_job_instances_post

        Create Job Instance
        """
        pass

    def test_create_provider_providers_post(self) -> None:
        """Test case for create_provider_providers_post

        Create Provider
        """
        pass

    def test_create_repository_repositories_post(self) -> None:
        """Test case for create_repository_repositories_post

        Create Repository
        """
        pass

    def test_delete_cluster_clusters_cluster_id_delete(self) -> None:
        """Test case for delete_cluster_clusters_cluster_id_delete

        Delete Cluster
        """
        pass

    def test_delete_job_instance_job_instances_job_instance_id_delete(self) -> None:
        """Test case for delete_job_instance_job_instances_job_instance_id_delete

        Delete Job Instance
        """
        pass

    def test_delete_provider_providers_provider_id_delete(self) -> None:
        """Test case for delete_provider_providers_provider_id_delete

        Delete Provider
        """
        pass

    def test_list_clusters_clusters_get(self) -> None:
        """Test case for list_clusters_clusters_get

        List Clusters
        """
        pass

    def test_list_job_instances_job_instances_get(self) -> None:
        """Test case for list_job_instances_job_instances_get

        List Job Instances
        """
        pass

    def test_list_providers_providers_get(self) -> None:
        """Test case for list_providers_providers_get

        List Providers
        """
        pass

    def test_list_providers_types_provider_types_get(self) -> None:
        """Test case for list_providers_types_provider_types_get

        List Providers Types
        """
        pass

    def test_list_repositories_repositories_get(self) -> None:
        """Test case for list_repositories_repositories_get

        List Repositories
        """
        pass

    def test_read_cluster_clusters_cluster_id_get(self) -> None:
        """Test case for read_cluster_clusters_cluster_id_get

        Read Cluster
        """
        pass

    def test_read_job_instance_job_instances_job_instance_id_get(self) -> None:
        """Test case for read_job_instance_job_instances_job_instance_id_get

        Read Job Instance
        """
        pass

    def test_read_provider_providers_provider_id_get(self) -> None:
        """Test case for read_provider_providers_provider_id_get

        Read Provider
        """
        pass

    def test_read_repository_repositories_repository_id_get(self) -> None:
        """Test case for read_repository_repositories_repository_id_get

        Read Repository
        """
        pass


if __name__ == '__main__':
    unittest.main()
