
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-12T09:35:08-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e5e0aa95298020a4b3983009d4aea046456dd036",
 "version": "2024.5.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
