# Generated by Django 3.2 on 2023-12-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbase_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_status',
            field=models.CharField(choices=[('发布', '发布'), ('草稿', '草稿'), ('垃圾桶', '垃圾桶')], default='published', max_length=10),
        ),
    ]
