#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2402-48-g08eec446"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2402
#define NETGEN_VERSION_TWEAK 48
#define NETGEN_VERSION_HASH "g08eec446"
#endif // NETGEN_VERSION_HPP_INCLUDED
