# Generated by Django 3.2 on 2024-03-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbase_post', '0005_auto_20240312_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='templ',
            field=models.TextField(default='\n            {{ post.data | safe }} \n            ---\n            {{ prompt_text }} \n        ', help_text='\n            模板文件可以使用 Jinja2 语法编写。\n\n            以下是一个示例模板：\n\n            ```\n            <h1>{{ title }}</h1>\n            <p>{{ description }}</p>\n            ```\n\n            可以使用以下变量：\n\n            * `title`: 提示标题\n            * `description`: 提示描述\n\n            可以使用以下过滤器：\n\n            * `safe`: 将文本转义为 HTML 安全格式\n            * `truncatechars`: 截断文本\n        ', verbose_name='模板文件'),
        ),
        migrations.AlterField(
            model_name='prompttask',
            name='prompts',
            field=models.ManyToManyField(default=[1], through='tbase_post.PromptTaskPrompt', to='tbase_post.Prompt'),
        ),
    ]
