
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-08T14:45:22-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5329a4f25b254a77bdead9401b69052d976915f9",
 "version": "2.36.0rc0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
